### PR TITLE
Do not validate customer object on save

### LINKED ISSUE #23: Error: The store that was requested wasn't found. Verify the store and try again.
Hi, i have found an issue in the module when saving the new password for a customer.

When updating the password for a customer in a multi-store setup, and customer is assigned to the non-default store, saving the new password fails. After some testing it appears that the issue can be resolved by skipping (address) validation when saving the customer, and it turns out Magento already does the same.

Magento skips address validation when the password is reset via default reset-password mechanism:
https://github.com/magento/magento2/blob/9c05217d05a7473a9b8731d70b77c3c84fdfa5e0/app/code/Magento/Customer/Model/AccountManagement.php#L716

This can be applied in this module as well, before calling save() on the customer repository:

https://github.com/tuyennn/magento2-change-customer-password/blob/14a2ad7259490c6959fb704ad6c983c10959f5ee/Controller/Adminhtml/Password/ChangePwdPost.php#L77

Let me know what you think of the proposal. I can provide a patch if needed.

### PR DESCRIPTION
**Pull request by marcoveeneman**
Do not validate customer object when saving new password, like magento's resetPassword method also does

Fixes #23 

## Summary by CodeRabbit

- **New Features**
  - Enhanced the password reset process to streamline account recovery by bypassing address validation, ensuring a smoother and more reliable experience.

### CODE REVIEW

File: Controller/Adminhtml/Password/ChangePwdPost.php [hunk 1]
```diff
@@ -32,23 +34,33 @@ class ChangePwdPost extends Action implements HttpPostActionInterface
...
-        EncryptorInterface $encryptor
+        EncryptorInterface $encryptor,
+        ?AddressRegistry $addressRegistry = null
     ) {
         $this->customerRepository = $customerRepository;
         $this->customerRegistry = $customerRegistry;
         $this->encryptor = $encryptor;
+        $objectManager = ObjectManager::getInstance();
+        $this->addressRegistry = $addressRegistry
+            ?: $objectManager->get(AddressRegistry::class);
```
Comment (tuyennn) [inline Controller/Adminhtml/Password/ChangePwdPost.php]: @marcoveeneman We don't need to keep $objectManager = ObjectManager::getInstance(); defined as a constructor, just remove it.

So in this case the

```
$this->addressRegistry = $addressRegistry
            ?: ObjectManager::getInstance()->get(AddressRegistry::class);
```            

just enough.

**Review by tuyennn — CHANGES_REQUESTED** [review]

**Comment by tuyennn** [comment]
@marcoveeneman thank you for creating the pull request, can you resolve the request changes above, then we can make it up to master branch

**Review by tuyennn — APPROVED** [review]
